

AWSTemplateFormatVersion: '2010-09-09'
Description: Infra Role
 
Parameters:
  IAMRoleName:
    Type: String
    Description: Role Name
    
Resources:
  EC2InstanceProfile:
    Properties:
      Roles:
      - Ref: IAMRoleName
    Type: AWS::IAM::InstanceProfile
  EC2InstanceRole:
    Properties:
      RoleName: !Ref IAMRoleName
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - s3:ListBucket
            Effect: Allow
            Resource:
             - !Sub arn:aws:s3:::amehan-ent
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource:
             - !Sub arn:aws:s3:::amahan-ent/*
          Version: '2012-10-17'
        PolicyName: EC2-S3-Download
      - PolicyDocument:
          Statement:
          - Action:
            - secretsmanager:GetSecretValue
            Effect: Allow
            Resource: 'arn:aws:secretsmanager:ca-central-1:*:secret:Windows/ServiceAccount/DomainJoin*'
          Version: '2012-10-17'
        PolicyName: SecretsManagerGet
    Type: AWS::IAM::Role
Outputs:
  
  EC2InstanceProfile:
    Description: Instance Profile name
    Value: !Ref EC2InstanceProfile
    Export: 
      Name: !Sub "${AWS::StackName}-EC2InstanceProfile"

  EC2InstanceRole:
    Description: Instance Role name
    Value: !Ref EC2InstanceRole
    Export: 
      Name: !Sub "${AWS::StackName}-EC2IAMRole"
      
  StackName:
    Description: StackName of this stack
    Value: !Ref AWS::StackName